# Generated by Django 3.1.4 on 2020-12-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0004_mytext_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='img_url',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
