# Generated by Django 3.1.4 on 2021-01-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflearn_lecture', '0007_auto_20210105_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mytext',
            name='lecture_video4',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
